# Site settings
title: Irving Barajas
email: irvingb232@gmail.com
description: Thinker // Designer // Photographer

# Build settings

markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :nested
